### ISSUE TITLE
Reentrancy?

### ISSUE THREAD

**Issue by kwesolowski** [rdpoor/ulog#1]
Is it expected to handle reentrancy (in the RTOS environment)?

**Comment by rdpoor** [comment]
@kwesolowski That's an astute question!  

No, ulog is not designed to intrinsically handle reentrancy, but if your logger functions are properly guarded, it should work with an RTOS.

However, ulog has been incorporated into `mu_log` in https://github.com/rdpoor/mulib, which is a run-to-completion RTOS in which reentrancy is not an issue.  (See https://github.com/rdpoor/mulib/blob/master/RunToCompletion.md for a manifesto on run to completion schedulers and how they compare to preemptive schedulers...)

**Comment by kwesolowski** [comment]
Thanks!
